#!/usr/bin/env python3
"""Write the shared fixtures the browser modules are checked against.

    python tests/export_js_fixtures.py && node web/tests/parity.test.mjs

The Python implementations are the oracle: this writes their answers for colour
distance, mixture planning, the paint codec and the G-code planner into
`web/tests/fixtures.json`, and the Node test compares the browser modules with
it.  Keeping the fixtures generated means the parity check cannot drift.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)

import u1colour                                                   # noqa: E402
import u1gcode                                                    # noqa: E402
import u1mix                                                      # noqa: E402
import u1paint                                                    # noqa: E402
import u1spectrum                                                 # noqa: E402

OUT = os.path.join(HERE, "web", "tests", "fixtures.json")

REELS = [
    {"slot": 1, "color": "#FFFFFF", "type": "PLA"},
    {"slot": 2, "color": "#000000", "type": "PLA"},
    {"slot": 3, "color": "#FF9500", "type": "PLA"},
    {"slot": 4, "color": "#FF0080", "type": "PLA"},
]

COLOUR_PAIRS = [
    ("#FF0000", "#000000"), ("#C8D8C0", "#3D9140"), ("#0080C0", "#637E9F"),
    ("#FFFFFF", "#FF9500"), ("#17BECF", "#8C564B"),
]

PAINT_VALUES = ["", "0", "4", "8", "C", "2C", "42C2CA442C4423", "1C",
                "4444444444444444444444444444444444"]

SCENARIOS = []


def _layer(index, z, tools, amount=1.0):
    out = [";LAYER_CHANGE\n", f";Z:{z}\n", ";HEIGHT:0.2\n",
           f";SET_PRINT_STATS_INFO CURRENT_LAYER:{index}\n",
           ";BEFORE_LAYER_CHANGE\n", "M83\n"]
    for tool in tools:
        out += [f"T{tool}\n", "G1 X10 Y10 F9000\n",
                f"G1 X20 Y10 E{amount:.3f}\n", "G1 E-0.5 F2100\n",
                f"G1 E0.5 F2100\n"]
    out.append(";AFTER_LAYER_CHANGE\n")
    return "".join(out)


def _scenario(name, text, physical=4):
    SCENARIOS.append({"name": name, "physical": physical, "gcode": text})


def build():
    _scenario("two tools, no changes",
              "; generated by OrcaSlicer 2.4.0\n; estimated printing time = 12m\n"
              + _layer(0, 0.2, [0, 1]) + _layer(1, 0.4, [0, 1]))
    _scenario("five tools across layers",
              "; PrusaSlicer 2.9.6\n"
              + "".join(_layer(i, 0.2 * (i + 1), [i]) for i in range(5)))
    _scenario("five colours in one layer",
              "".join(_layer(0, 0.2, list(range(5)))))
    _scenario("startup and a sentinel",
              "T1\nG1 X1 Y1 F9000\nG1 X5 Y1 E0.4 F1200\nM600\n"
              + _layer(0, 0.2, [0]) + _layer(1, 0.4, [1, 2, 3]))
    _scenario("supports add a colour",
              "".join(_layer(0, 0.2, [0, 2])) + ";TYPE:SUPPORT\nT3\n"
              "G1 X30 Y10 E1.2 F1800\n")
    _scenario("hook-only dialect",
              ";BEFORE_LAYER_CHANGE\n;Z:0.2\n;HEIGHT:0.2\nM83\nT0\n"
              "G1 X5 Y5 E1.0\n;AFTER_LAYER_CHANGE\n"
              ";BEFORE_LAYER_CHANGE\n;Z:0.4\n;HEIGHT:0.2\nT1\n"
              "G1 X6 Y5 E1.0\n;AFTER_LAYER_CHANGE\n")
    _scenario("uncommented stats and height",
              "SET_PRINT_STATS_INFO TOTAL_LAYER=2\n"
              ";LAYER_CHANGE\n;Z:0.2\n;HEIGHT:0.16\n"
              "SET_PRINT_STATS_INFO CURRENT_LAYER=0\nM83\nT0\nG1 X5 Y5 E1.0\n"
              ";LAYER_CHANGE\n;Z:0.36\n;HEIGHT:0.16\nT1\nG1 X6 Y5 E1.0\n")
    _scenario("retract debt and a full circle",
              ";LAYER_CHANGE\n;Z:0.2\nM83\nT0\nG1 X5 Y5 E1.0\n"
              "G1 E-1.0\nG1 E1.0\nG1 E0.4\nG2 I1 J0 E0.8\n")
    _scenario("startup purge",
              ";LAYER_CHANGE\n;Z:0.2\nT2\nG1 X1 Y1 F9000\nG1 E5.0\n"
              "T0\nG1 X5 Y5 E1.0\n")
    _scenario("m600 and a pause",
              _layer(0, 0.2, [0]) + "M600\n;LAYER_CHANGE\n;Z:0.4\nM0\nT0\n"
              "G1 X5 Y5 E1.0\n")
    _scenario("refuses G90.1", ";LAYER_CHANGE\nG90.1\nG1 X5 Y5 E1.0\n")
    _scenario("refuses a sentinel tool", ";LAYER_CHANGE\nT255\nG1 X5 Y5 E1.0\n")
    _scenario("refuses a malformed move", ";LAYER_CHANGE\nG1 X Y5 E1.0\n")


def main() -> int:
    build()
    fixtures = {
        "colour": {
            "pairs": [
                {"a": a, "b": b,
                 "distance": round(u1colour.distance(a, b), 6)}
                for a, b in COLOUR_PAIRS
            ],
            "nearest": [
                {"target": "#C8D8C0",
                 "palette": [r["color"] for r in REELS],
                 "index": u1colour.nearest("#C8D8C0",
                                           [r["color"] for r in REELS])[0]}
            ],
        },
        "mix": {
            "reels": REELS,
            "cases": [
                {"sources": {"1": "#FF0000"}, "expected":
                    _mix_expected({"1": "#FF0000"})},
                {"sources": {"1": "#C8D8C0"}, "expected":
                    _mix_expected({"1": "#C8D8C0"})},
                {"sources": {"1": "#B03060", "2": "#FFFFFF"}, "expected":
                    _mix_expected({"1": "#B03060", "2": "#FFFFFF"})},
            ],
            "hexes": [
                {"a": "#FFFFFF", "b": "#000000", "percent": percent,
                 "color": u1mix.mix_hex("#FFFFFF", "#000000", percent)}
                for percent in (25, 50, 75)
            ],
        },
        "paint": {
            "supported_max": u1paint.SUPPORTED_STATE_MAX,
            "excessive": [
                {"value": value,
                 "states": u1paint.excessive_states(value)}
                for value in PAINT_VALUES if value
            ],
            "decoded": [
                {"value": value, "tree": _safe_decode(value)}
                for value in PAINT_VALUES
            ],
            "remapped": [
                {"value": value, "mapping": {"1": 2, "3": 4, "4": 5},
                 "result": _safe_remap(value, {1: 2, 3: 4, 4: 5})}
                for value in PAINT_VALUES
            ],
        },
        "spectrum": {
            "max_visible": u1spectrum.MAX_VISIBLE,
            "max_recipes": u1spectrum.MAX_RECIPES,
            "virtual_id": [{"physical": 4, "index": index,
                            "id": u1spectrum.virtual_id(4, index)}
                           for index in range(4)],
        },
        "planner": [
            {"name": item["name"], "physical": item["physical"],
             "gcode": item["gcode"], "expected": _planner_expected(item)}
            for item in SCENARIOS
        ],
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(fixtures, fh, indent=1, sort_keys=True)
    print(f"{OUT}: {os.path.getsize(OUT)} bytes")
    write_projects()
    return 0


def write_projects() -> None:
    """The small synthetic projects the browser-side reader is checked against."""
    from tests import fixtures as fx

    folder = os.path.dirname(OUT)
    os.makedirs(folder, exist_ok=True)
    targets = {
        "five-colours.3mf": lambda path: fx.two_plate_project(path, five_colours=True),
        "four-colours.3mf": lambda path: fx.two_plate_project(path),
        # The palette the browser Prusa test uses paints states 4 and 5, so entry 4
        # is a colour the mixer can actually improve on: that keeps the exported
        # recipe path (virtual extruder ids, ratios) under test rather than empty.
        "single-object.3mf": lambda path: fx.single_object_project(
            path, colors=["#FFFFFF", "#000000", "#FF9500", "#FF0080", "#004400",
                          "#0000FF"]),
        # A rotation *and* a translation, so the preview matrix is checked rather
        # than assumed: see web/tests/project.test.mjs and tests/test_u1preview.py.
        "rotated.3mf": lambda path: fx.rotated_preview_project(path),
        # PrusaSlicer volume ranges this tool refuses to read as whole meshes.
        "prusa-negative.3mf": lambda path: fx.prusa_negative_volume_project(path),
        # A nested assembly (a component that is itself built from components).
        "nested.3mf": lambda path: fx.nested_project(path),
        # A wide row of tiles: with a tiny cap the sample must still span the row.
        "wide-quad.3mf": lambda path: fx.wide_quad_project(path),
        # Paint naming a colour the palette does not describe.  (Not "out-*.3mf":
        # that name belongs to the exports the browser test writes.)
        "paint-beyond-palette.3mf": lambda path: fx.out_of_palette_paint_project(path),
    }
    for name, build in targets.items():
        path = os.path.join(folder, name)
        build(path)
        print(f"{path}: {os.path.getsize(path)} bytes")


def _mix_expected(sources):
    plan = u1mix.plan_mixtures({int(k): v for k, v in sources.items()}, REELS)
    return {
        "advice": plan["advice"],
        "recipes": [{"id": r["id"], "a": r["a"], "b": r["b"],
                     "percent": r["percent"], "color": r["color"]}
                    for r in plan["recipes"]],
        "rows": [{"source": row["source"], "choice": row["choice"],
                  "recipe_id": row.get("recipe_id"),
                  "solid_slot": row["solid"]["slot"],
                  "solid_error": row["solid"]["error"]}
                 for row in plan["rows"]],
    }


def _safe_decode(value):
    if not value:
        return None
    try:
        return _tree(u1paint.decode(value))
    except u1paint.PaintError:
        return "error"


def _tree(node):
    if node[0] == "leaf":
        return {"kind": "leaf", "state": node[1]}
    return {"kind": "split", "sides": node[1], "specialSide": node[2],
            "children": [_tree(child) for child in node[3]]}


def _safe_remap(value, mapping):
    if not value:
        return value
    try:
        return u1paint.remap_text(value, mapping)
    except u1paint.PaintError:
        return "error"


def _planner_expected(item):
    try:
        result = u1gcode.analyse(item["gcode"], physical=item["physical"])
    except u1gcode.GcodeError as exc:
        return {"error": str(exc)}
    keys = ("feasible", "layers", "tools", "initial", "schedule", "pause_count",
            "reel_changes", "startup_tools", "max_tools_per_layer",
            "incompatible_count", "primes", "retractions", "stats_layer_markers",
            "diagnosis", "summary", "flavour", "anomalies", "total_layers",
            "legend", "per_layer", "sentinels")
    return {k: result.get(k) for k in keys}


if __name__ == "__main__":
    sys.exit(main())
