"""The sliced-G-code planner: what counts as a colour, and what is refused."""

import unittest

import u1gcode

HEADER = ("; generated by OrcaSlicer 2.4.0\n"
          "; estimated printing time (normal mode) = 1h 2m 3s\n")


def layer(index, z, tools, *, height=True, stats=True, pre=""):
    """One logical layer, with the metadata markers a real slicer writes."""
    out = [f";LAYER_CHANGE\n", f";Z:{z}\n"]
    if height:
        out.append(f";HEIGHT:0.2\n")
    if stats:
        out.append(f";SET_PRINT_STATS_INFO CURRENT_LAYER:{index}\n")
    out.append(";BEFORE_LAYER_CHANGE\n")
    out.append(pre)
    out.append("M83\n")           # relative extrusion: each deposit stands alone
    for tool, amount in tools:
        out.append(f"T{tool}\n")
        out.append("G1 X10 Y10 F9000\n")
        out.append(f"G1 X20 Y10 E{amount:.3f}\n")
        out.append("G1 E-0.5 F2100\n")
        out.append("G1 E0.5 F2100\n")
    out.append(";AFTER_LAYER_CHANGE\n")
    return "".join(out)


class Analyse(unittest.TestCase):
    def test_commands_are_matched_exactly(self):
        """G90.1 is not G90, M820 is not M82, and a bare axis letter is malformed."""
        cases = {
            "g90.1": (";LAYER_CHANGE\nG90.1\nG1 X1 Y1 E1\n", u1gcode.GcodeError,
                      "G90.1"),
            "activate": (";LAYER_CHANGE\nACTIVATE_EXTRUDER EXTRUDER=extruder1\n"
                         "G1 X1 Y1 E1\n", u1gcode.GcodeError, "ACTIVATE_EXTRUDER"),
            "conditional": (";LAYER_CHANGE\nM622 J1\nG1 X1 Y1 E1\n",
                            u1gcode.GcodeError, "M620-M623"),
            "sentinel tool": (";LAYER_CHANGE\nT255\nG1 X1 Y1 E1\n",
                              u1gcode.GcodeError, "sentinel"),
            "malformed": (";LAYER_CHANGE\nG1 X Y1 E1\n", u1gcode.GcodeError,
                          "no number"),
        }
        for name, (payload, error, needle) in cases.items():
            with self.subTest(name):
                with self.assertRaises(error) as caught:
                    u1gcode.analyse(payload)
                self.assertIn(needle, str(caught.exception))

    def test_m820_is_not_m82_and_is_refused(self):
        # M810-M819 are user macros: one that merely starts with M82 must not
        # switch modes, and it must not be skipped either, because a macro can do
        # anything to extrusion or the tool.
        text = (";LAYER_CHANGE\nM83\nT0\nG1 X0 Y0 E1.0\nM820\nG1 X1 Y1 E1.0\n")
        with self.assertRaises(u1gcode.GcodeError) as caught:
            u1gcode.analyse(text)
        self.assertIn("M820", str(caught.exception))

    def test_unretraction_is_not_a_prime_but_extra_material_is(self):
        text = (";LAYER_CHANGE\nM83\nT0\n"
                "G1 X5 Y5 E1.0\n"         # deposit
                "G1 E-1.0\n"              # retract: debt 1
                "G1 E1.0\n"               # unretract: debt cleared, not a prime
                "G1 E0.4\n"               # extra material, no movement: a prime
                "G1 X1 Y1 E1.0\n")        # deposit
        result = u1gcode.analyse(text)
        self.assertEqual(1, result["retractions"])
        self.assertEqual(1, result["primes"])
        self.assertEqual(0, result["anomalies"])

    def test_depositing_with_retract_debt_is_reported(self):
        # A move that deposits exactly what a retraction took out is a *payback*,
        # not a colour of its own, but printing through a retracted nozzle is still
        # worth reporting.  (A file with nothing but the payback has no material at
        # all and is refused; this one has a real deposit first.)
        text = (";LAYER_CHANGE\nM83\nT0\nG1 X5 Y5 E1.0\n"
                "G1 E-1.0\nG1 X1 Y1 E1.0\n")
        result = u1gcode.analyse(text)
        self.assertEqual(1, result["anomalies"])
        self.assertEqual([0], result["per_layer"][0]["tools"])

    def test_a_full_circle_arc_deposits(self):
        text = (";LAYER_CHANGE\nM83\nT0\nG2 I1 J0 E0.8\n")
        result = u1gcode.analyse(text)
        self.assertEqual([0], result["tools"])

    def test_startup_purge_asks_for_its_reel(self):
        text = ("T2\nG1 X1 Y1 F9000\nG1 E5.0\n"      # purge before any layer
                ";LAYER_CHANGE\n;Z:0.2\nT0\nG1 X1 Y1 E1.0\n")
        result = u1gcode.analyse(text)
        self.assertEqual([2], result["startup_tools"])
        self.assertIn("2", result["initial"], "the purge reel loads at the start")

    def test_only_the_after_hook_counts_when_that_is_all_there_is(self):
        text = (";BEFORE_LAYER_CHANGE\n;Z:0.2\nM83\nT0\nG1 X1 Y1 E1.0\n"
                ";AFTER_LAYER_CHANGE\n;BEFORE_LAYER_CHANGE\n;Z:0.4\n"
                "G1 X1 Y1 E1.0\n;AFTER_LAYER_CHANGE\n")
        result = u1gcode.analyse(text)
        self.assertEqual(2, result["layers"], "before+after is not two layers")
        self.assertEqual([0.2, 0.4], [entry["z"] for entry in result["per_layer"]])

    def test_uncommented_stats_markers_and_height_are_metadata(self):
        text = ("SET_PRINT_STATS_INFO TOTAL_LAYER=2\n"
                ";LAYER_CHANGE\n;Z:0.2\n;HEIGHT:0.16\n"
                "SET_PRINT_STATS_INFO CURRENT_LAYER=0\nM83\nT0\nG1 X1 Y1 E1.0\n"
                ";LAYER_CHANGE\n;Z:0.36\n;HEIGHT:0.16\nT0\nG1 X2 Y1 E1.0\n")
        result = u1gcode.analyse(text)
        self.assertEqual(2, result["layers"])
        self.assertEqual(1, result["stats_layer_markers"],
                         "the uncommented CURRENT_LAYER marker is counted once")
        self.assertEqual(2, result["total_layers"])
        self.assertEqual([0.16, 0.16], [entry["height"] for entry in result["per_layer"]])
        self.assertEqual([0.2, 0.36], [entry["z"] for entry in result["per_layer"]])

    def test_layer_and_change_line_numbers_are_reported(self):
        text = HEADER + "".join(
            layer(index, 0.2 * (index + 1), [(index, 1.0)]) for index in range(5))
        result = u1gcode.analyse(text)
        self.assertEqual(1, result["schedule"][0]["line"] > 0)
        for entry in result["per_layer"]:
            self.assertGreater(entry["line"], 0)
    def test_one_logical_layer_per_layer_marker(self):
        text = HEADER + layer(0, 0.2, [(0, 1.0)]) + layer(1, 0.4, [(0, 1.0)])
        result = u1gcode.analyse(text)
        self.assertEqual(2, result["layers"])
        self.assertEqual(2, result["stats_layer_markers"])
        self.assertTrue(result["feasible"])
        self.assertEqual([0], result["tools"])
        self.assertEqual({"0": 1}, result["initial"])
        self.assertEqual("1h 2m 3s", result["reported_time"])
        self.assertEqual("orca", result["flavour"])

    def test_retractions_primes_and_travel_are_not_colours(self):
        text = (HEADER
                + ";LAYER_CHANGE\n;Z:0.2\nT0\n"
                  "G1 X5 Y5 F9000\n"            # travel
                  "G1 E2 F2100\n"               # prime, no travel
                  "G1 E-1 F2100\n"              # retract
                  "G1 E-2 F2100\n"              # retract again
                  "G1 X20 Y5 F9000\n"           # travel
                  "G1 X30 Y5 E1.5 F1800\n")     # the only deposition
        result = u1gcode.analyse(text)
        self.assertEqual([0], result["tools"])
        self.assertEqual(1, result["primes"])
        self.assertEqual(2, result["retractions"])

    def test_startup_deposition_is_kept(self):
        text = (HEADER
                + "T1\nG1 X1 Y1 F9000\nG1 X5 Y1 E0.4 F1200\n"       # skirt before layers
                  ";LAYER_CHANGE\n;Z:0.2\nT0\nG1 X10 Y10 E1.0 F1800\n")
        result = u1gcode.analyse(text)
        self.assertEqual([1], result["startup_tools"])
        self.assertEqual([0, 1], result["tools"])
        self.assertIn("1", result["initial"], "the skirt colour loads at the start")

    def test_relative_extrusion_and_g92(self):
        text = (";LAYER_CHANGE\n;Z:0.2\nM83\nT0\nG1 X10 Y10 E0.5\nG1 X20 Y10 E0.5\n"
                ";LAYER_CHANGE\n;Z:0.4\nG92 E0\nM82\nG1 X10 Y10 E1.0\n")
        result = u1gcode.analyse(text)
        self.assertEqual(2, result["layers"])
        self.assertEqual([0], result["tools"])

    def test_five_tools_across_layers_get_a_plan(self):
        text = HEADER + "".join(
            layer(index, 0.2 * (index + 1), [(index, 1.0)]) for index in range(5))
        result = u1gcode.analyse(text)
        self.assertTrue(result["feasible"], result.get("summary"))
        self.assertEqual(4, len(result["initial"]), "four reels load at the start")
        self.assertEqual(1, result["reel_changes"])
        self.assertEqual(1, result["pause_count"])
        change = result["schedule"][0]
        self.assertEqual(4, change["in"], "the fifth colour is introduced last")
        self.assertEqual(0, change["out"], "the reel used earliest is the one reused")

    def test_a_layer_with_five_colours_has_no_plan(self):
        text = HEADER + layer(0, 0.2, [(t, 1.0) for t in range(5)])
        result = u1gcode.analyse(text)
        self.assertFalse(result["feasible"])
        self.assertEqual([], result["schedule"])
        self.assertIsNone(result["pause_count"])
        self.assertEqual(1, result["incompatible_count"])
        self.assertEqual("too-many-colours-per-layer", result["diagnosis"])
        self.assertIn("cannot be separated", result["summary"])

    def test_supports_and_infill_count_as_colour_use(self):
        text = (HEADER + ";LAYER_CHANGE\n;Z:0.2\nT0\nG1 X10 Y10 E1.0 F1800\n"
                ";TYPE:SUPPORT\nT2\nG1 X20 Y10 E2.0 F1800\n")
        result = u1gcode.analyse(text)
        self.assertEqual([0, 2], result["tools"])

    def test_m600_is_an_operator_action_not_a_colour(self):
        text = (HEADER + ";LAYER_CHANGE\n;Z:0.2\nT0\nG1 X10 Y10 E1.0 F1800\n"
                "M600\n")
        result = u1gcode.analyse(text)
        self.assertEqual([0], result["tools"])
        self.assertEqual(1, len(result["sentinels"]))
        self.assertEqual("filament-change", result["sentinels"][0]["kind"])
        self.assertEqual(0, result["sentinels"][0]["layer"])
        self.assertIn("M600", u1gcode.plan_text(result, "x"))

    def test_refusals_are_sentences(self):
        cases = {
            "binary": (b"\x00\x01\x02", u1gcode.decode),
            "empty": (b"", u1gcode.decode),
            "no layers": ("G1 X1 Y1 E1\n" * 4, u1gcode.analyse),
            "no deposition": (";LAYER_CHANGE\n;Z:0.2\nG1 X1 Y1\n", u1gcode.analyse),
            "inches": (";LAYER_CHANGE\nG20\nG1 X1 Y1 E1\n", u1gcode.analyse),
            "volumetric": (";LAYER_CHANGE\nM200 D1.75\nG1 X1 Y1 E1\n",
                           u1gcode.analyse),
            "firmware retract": (";LAYER_CHANGE\nG10\nG1 X1 Y1 E1\n", u1gcode.analyse),
        }
        for name, (payload, fn) in cases.items():
            with self.subTest(name):
                with self.assertRaises(u1gcode.GcodeError) as caught:
                    fn(payload)
                self.assertTrue(str(caught.exception))

    def test_unknown_commands_and_mode_lookalikes_are_refused(self):
        """A command this planner does not model must not be skipped silently.

        M810-M819 are user macros and `G91.1` is not `G91`: either could change
        extrusion or the tool, so a plan that ignored them would be confident
        about a file it never really read.
        """
        header = "; generated by OrcaSlicer 2.4.0\n; gcode_flavor = klipper\n"
        for command in ("G91.1", "M820", "M1002 gcode_claim_action = 1"):
            with self.subTest(command):
                text = header + f";LAYER_CHANGE\n{command}\nG1 X1 Y1 E1\n"
                with self.assertRaises(u1gcode.GcodeError) as caught:
                    u1gcode.analyse(text)
                self.assertIn(command.split()[0], str(caught.exception))

    def test_passive_commands_are_ignored_on_purpose(self):
        header = "; generated by OrcaSlicer 2.4.0\n; gcode_flavor = klipper\n"
        text = (header + ";LAYER_CHANGE\nG28\nM104 S200\nM106 S255\n"
                "SET_PRESSURE_ADVANCE ADVANCE=0.04\nEXCLUDE_OBJECT_START NAME=x\n"
                "M83\nT0\nG1 X1 Y1 E1\nEXCLUDE_OBJECT_END NAME=x\n")
        self.assertEqual([0], u1gcode.analyse(text)["tools"])

    def test_g92_accepts_a_tab_between_the_command_and_its_arguments(self):
        text = (";LAYER_CHANGE\nM83\nT0\nG1 X1 Y1 E1\nG92\tE0\nG1 X2 Y1 E1\n")
        self.assertEqual([0], u1gcode.analyse(text)["tools"])

    def test_extrusion_mode_after_a_mode_change_is_not_guessed(self):
        # A file that names no flavour and never says M82/M83 after G90/G91 leaves
        # the reading of its E words ambiguous.
        ambiguous = "; generated by PrusaSlicer\n;LAYER_CHANGE\nG91\nG1 X1 Y1 E1\n"
        with self.assertRaises(u1gcode.GcodeError) as caught:
            u1gcode.analyse(ambiguous)
        self.assertIn("absolute or relative", str(caught.exception))
        # Marlin resets E with the move mode, so the same file with a Marlin
        # flavour is readable.
        marlin = ("; generated by PrusaSlicer\n; gcode_flavor = marlin\n"
                  ";LAYER_CHANGE\nG90\nT0\nG1 X1 Y1 E1\n")
        self.assertEqual([0], u1gcode.analyse(marlin)["tools"])
        # ... and a legacy file with no G90/G91 at all keeps working.
        legacy = ";LAYER_CHANGE\nM83\nT0\nG1 X1 Y1 E1\n"
        self.assertEqual([0], u1gcode.analyse(legacy)["tools"])

    def test_plan_text_does_not_call_an_included_prime_ignored(self):
        header = "; generated by OrcaSlicer 2.4.0\n; gcode_flavor = klipper\n"
        result = u1gcode.analyse(header + ";LAYER_CHANGE\nM83\nT0\nG1 E1\n"
                                 "G1 X5 Y5 E1\nT4\nG1 X6 Y5 E1\n")
        out = u1gcode.plan_text(result, "x")
        primes_line = [line for line in out.splitlines() if "prime moves" in line][0]
        self.assertIn("counted as material", primes_line)
        self.assertNotIn("ignored", primes_line)

    def test_plan_text_is_human_readable_and_never_gcode(self):
        text = HEADER + "".join(
            layer(index, 0.2 * (index + 1), [(index, 1.0)]) for index in range(5))
        result = u1gcode.analyse(text)
        out = u1gcode.plan_text(result, "five.3mf")
        self.assertIn("Initial load", out)
        self.assertIn("reel change", out)
        # The old text told the user to "change reels when you print it" on G-code
        # that still selects virtual tools. The plan must say what is really needed.
        self.assertIn("This is a PLAN, not printable G-code.", out)
        self.assertIn("have to be remapped", out)
        self.assertIn("verified", out)
        self.assertIn("does not make it four-tool compatible", out)
        self.assertIn("(line ", out)
        self.assertNotIn("G1 ", out)

    def test_provenance_changes_with_the_review(self):
        first = u1gcode.provenance("a.3mf", {"plate": 1, "objects": ["10"]}, {"1": 2})
        second = u1gcode.provenance("a.3mf", {"plate": 1, "objects": ["11"]}, {"1": 2})
        self.assertNotEqual(first, second)
        self.assertEqual(first, u1gcode.provenance(
            "a.3mf", {"objects": ["10"], "plate": 1}, {"1": 2}))


if __name__ == "__main__":
    unittest.main()
