import assert from 'node:assert/strict';
import {recommendPalette, paletteScore} from '../shared/recommend.js';
const loaded=['#FFFFFF','#000000','#3D9140','#FF9500'].map(color=>({color,type:'PLA'}));
const alien={1:'#0080C0',2:'#FF0000',3:'#FFFFFF',4:'#000000',5:'#C5C263'};
const before=JSON.stringify({alien,loaded});
const impossible=recommendPalette({sources:alien,loaded});
assert.equal(impossible.found,false);
assert.equal(impossible.reels,undefined);
assert.deepEqual(impossible.alternatives,[]);
assert(impossible.search.evaluated>2000);
assert.equal(JSON.stringify({alien,loaded}),before);
// Known Prusa reference: cyan + yellow -> green. Search all reels jointly.
const sources={1:'#009BC3',2:'#F6B921',3:'#FFFFFF',4:'#000000',5:'#519E5F'};
const start=performance.now();
const rough=recommendPalette({sources,loaded});
assert(rough.found && rough.rough); assert.equal(rough.reels.length,4);
assert(rough.score<rough.loadedScore);
const ranked=[rough,...rough.alternatives];
assert(ranked.length>=1 && ranked.length<=6);
assert.equal(new Set(ranked.map(p=>p.reels.map(r=>r.color).sort().join(','))).size,ranked.length);
ranked.forEach((p,i)=>{
  assert.equal(p.unresolved,0);
  assert.equal(p.outcome.counts.substituted,0);
  assert.equal(p.score,paletteScore(sources,p.reels));
  assert(p.outcome.blendCount>0);
  if(i) assert(p.score>=ranked[i-1].score);
});
const stock=rough.reels.map((r,i)=>({...r,name:`Brand ${i} · ${r.name}`}));
stock.push({color:'#FFFF00',type:'PETG',name:'Other material'});
const owned=recommendPalette({sources,loaded,stock});
assert(owned.found && !owned.rough);
assert(owned.reels.every(r=>stock.some(s=>s.name===r.name && s.color===r.color)));
assert.equal(new Set(owned.reels.map(r=>r.type)).size,1);
const locks=[false,true,false,true];
const locked=recommendPalette({sources,loaded:owned.reels,stock,locked:locks});
assert(locked.found);
for(const p of [locked,...locked.alternatives]) locks.forEach((lock,i)=>{if(lock) assert.deepEqual(p.reels[i],owned.reels[i]);});
const incompatible=recommendPalette({sources,loaded,stock,locked:[true,true,true,true]});
assert.equal(incompatible.found,false);
assert.equal(recommendPalette({sources,loaded,stock:[]}).found,false);
assert.throws(()=>recommendPalette({sources:{},loaded}),/readable/);
assert.throws(()=>recommendPalette({sources,loaded:[loaded[0],{...loaded[1],type:'PETG'},...loaded.slice(2)],locked:[true,true]}),/different materials/);
const exact=Object.fromEntries(loaded.map((r,i)=>[i+1,r.color]));
const unchanged=recommendPalette({sources:exact,loaded});
assert.equal(unchanged.score,0); assert.deepEqual(unchanged.reels.map(r=>r.color),loaded.map(r=>r.color));
const solid=recommendPalette({sources:alien,loaded,blends:false});
assert(solid.found && solid.outcome.counts.substituted>0);
assert.equal(solid.unresolved,0);
// Large libraries retain a diverse bounded pool and only offer owned colours.
const bigStock=Array.from({length:74},(_,i)=>({color:'#'+((i*221123)%0xffffff).toString(16).padStart(6,'0'),type:'PLA',name:'Stock '+i}));
bigStock.push(...stock);
const large=recommendPalette({sources,loaded,stock:bigStock});
assert(large.search.bounded); assert(large.search.evaluated<60000);
if(large.found) for(const p of [large,...large.alternatives]) assert(p.reels.every(r=>bigStock.some(s=>s.color.toUpperCase()===r.color)));
console.log('Recommendation checks passed: complete sets only, joint search, owned stock, locks, materials, empty state, solids, no mutation. '+Math.round(performance.now()-start)+'ms');
