import assert from "node:assert/strict";
import { readProject, convertProject, SRC_BBL_PROJECT } from "../shared/project.js";
import { prepareSwapProject } from "../shared/swapProject.js";
import { buildSwapExport, inspectU1, verifySwapExport } from "../shared/swapExport.js";
export function fixture(sequence = [[0,1,2,3], [0,1,2,4], [0,1,2,3]]) {
  const lines = ["; generated by OrcaSlicer", "PRINT_START", "M83", "G90", "T0",
    "SM_PRINT_AUTO_FEED EXTRUDER=0", "G1 X0 Y0 Z0.2 F3000"];
  sequence.forEach((tools, layer) => {
    lines.push(";LAYER_CHANGE", `;Z:${(layer + 1) * .2}`, ";HEIGHT:0.2",
      ";BEFORE_LAYER_CHANGE", "G92 E0", ";AFTER_LAYER_CHANGE",
      `SET_PRINT_STATS_INFO CURRENT_LAYER=${layer + 1}`, ";_SET_FAN_SPEED_CHANGING_LAYER");
    tools.forEach((tool, n) => lines.push(`M109 S210 T${tool}`, `T${tool}`,
      `SM_PRINT_PREEXTRUDE_FILAMENT INDEX=${tool}`, `G1 X${10 + n} Y${layer + 2} E1 F1200`));
  });
  lines.push("PRINT_END", "TIMELAPSE_STOP", "; printer_model = Snapmaker U1",
    "; gcode_flavor = klipper", "; filament_colour = #FFFFFF;#000000;#00FF00;#FF0000;#0000FF",
    "; filament_type = PLA;PLA;PLA;PLA;PLA", "; nozzle_diameter = 0.4,0.4,0.4,0.4,0.4");
  return lines.join("\n");
}
const src = fixture(), built = buildSwapExport(src);
assert.equal(built.evidence.pause_count, 2);
assert.equal((built.gcode.match(/^M600$/gm)||[]).length, 2);
assert.ok(!/^T[4-9]$/m.test(built.gcode));
assert.ok(!/^M109 .*T4$/m.test(built.gcode));
assert.ok(!/^SM_PRINT_PREEXTRUDE_FILAMENT INDEX=4$/m.test(built.gcode));
assert.match(built.sheet, /slot 4, remove colour 4.*load colour 5/i);
assert.match(built.sheet, /slot 4, remove colour 5.*load colour 4/i);
assert.equal(built.gcode.match(/^; filament_colour = (.*)$/m)[1].split(';').length,4);
const source = inspectU1(src);
const preamble = 'EXCLUDE_OBJECT_DEFINE NAME=alien CENTER=0,0 POLYGON=[[0,0],[1,0],[0,1]]\nM73 P0 R1\nM106 S0\nM106 P2 S0\n';
const realDialect = preamble + src.replace('M83', 'M83\nG17');
const realBuilt = buildSwapExport(realDialect);
assert.ok(realBuilt.gcode.includes(preamble));
assert.ok(realBuilt.gcode.includes('\nG17\n'));
assert.throws(() => buildSwapExport('M106 S255\n' + src), /before PRINT_START/);
assert.throws(() => buildSwapExport(src.replace('M83', 'M83\nG18')), /does not model/);
const impossible = inspectU1(fixture([[0,1,2,3,4]]));
assert.equal(impossible.evidence.feasible, false);
assert.match(impossible.evidence.summary, /actually deposit/);
assert.equal(impossible.evidence.incompatible_count, 1);
assert.equal(verifySwapExport(source,built.gcode),true);
for (const corrupted of [built.gcode.replace('G1 X10 Y2 E1','G1 X10 Y2 E9'),
  built.gcode.replace(/^M600$/m,'M0'), built.gcode.replace('M109 S210 T3','M109 S210 T2'),
  built.gcode.replace('; YAB3D_SWAP_END','G1 X100 E100'), built.gcode+'\nM600'])
  { assert.notEqual(corrupted,built.gcode, "tamper must change file"); assert.throws(()=>verifySwapExport(source,corrupted),/verification failed/); }
for (const [bad, message] of [
  [src.replace('Snapmaker U1','Bambu X1'),'U1'],
  [src.replace('M83','M82'),'Absolute'],
  [src.replace('PLA;PLA','PLA;PETG'),'all-PLA'],
  [src.replace('0.4,0.4','0.6,0.4'),'0.4 mm'],
  [src.replace('M83','M83\nM600'),'already contains'],
  [src.replace('M83','M83\nCUSTOM_PURGE'),'does not model'],
  [src.replace('M109 S210 T4','M109 S210 t4'),'unsupported heater'],
  [src.replace('M109 S210 T4','M109 S210 T-1'),'ambiguous heater'],
  [src.replace('M109 S210 T4','M109 S210 T+4'),'ambiguous heater'],
  [src.replace('M109 S210 T4','M109 S210 T4.0'),'ambiguous heater'],
  [src.replace('M109 S210 T4','M109 S210 T4 T0'),'ambiguous heater'],
  [src.replace('M83','M83\nACTIVATE_EXTRUDER EXTRUDER=extruder4'),'named-extruder'],
  [src.replace('CURRENT_LAYER=2','CURRENT_LAYER=3'),'disagree'],
  [src+'\n; mixed_filament_definitions = native blend','mixed filaments'],
  [built.gcode,'already has'],
  [fixture([[0,1,2,3,4]]),'5 colours'],
]) assert.throws(()=>buildSwapExport(bad),new RegExp(message));
// Missing T command cannot leave the previous colour on an evicted head.
const implicit=fixture([[0,1,2,3],[4,0,1,2]]).replace('M109 S210 T4\nT4','M109 S210 T4');
assert.throws(()=>buildSwapExport(implicit),/5 colours/);
const unused = buildSwapExport(fixture([[0,1,2,3]]));
assert.deepEqual(unused.evidence.unused_colours,[4]);
assert.match(unused.sheet,/Unused colours/);
assert.ok(!("4" in unused.evidence.initial));
assert.equal(unused.evidence.pause_count,0);
// A purge-only colour is still used, even without a painted surface move.
const purgeOnly = fixture([[0,1,2]]).replace("PRINT_END", "SM_PRINT_PREEXTRUDE_FILAMENT INDEX=4\nPRINT_END");
assert.deepEqual(buildSwapExport(purgeOnly).evidence.unused_colours,[3]);
console.log('swap export: two-pause replay, tools/heaters/purge, tampering and unsupported input passed');

const enc = new TextEncoder(), dec = new TextDecoder();
const entries = new Map([
  ["3D/3dmodel.model",enc.encode('<model xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" unit="millimeter"><resources><object id="1" type="model"><mesh><vertices><vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/><vertex x="0" y="10" z="5"/></vertices><triangles><triangle v1="0" v2="1" v3="2" paint_color="4"/></triangles></mesh></object></resources><build><item objectid="1"/></build></model>')],
  [SRC_BBL_PROJECT,enc.encode(JSON.stringify({filament_colour:['#FFFFFF','#000000','#00FF00','#FF0000','#0000FF'],filament_type:Array(5).fill('PLA'),layer_height:'0.24',enable_support:'1'}))],
]);
const parsed = readProject(entries);
const prepared = prepareSwapProject(parsed,parsed.plates[0].id,null);
const cfg=JSON.parse(dec.decode(prepared.entries.get(SRC_BBL_PROJECT)));
assert.equal(cfg.nozzle_diameter.length,5);
assert.deepEqual(cfg.printer_extruder_id,['1','2','3','4','5']);
assert.equal(cfg.different_settings_to_system.length,7);
assert.match(cfg.different_settings_to_system[0],/layer_height/);
assert.match(cfg.different_settings_to_system[6],/printer_extruder_id/);
assert.equal(cfg.layer_height,'0.24');
assert.equal(cfg.enable_support,'1');
assert.match(cfg.printer_settings_id,/SLICE ONLY/);
assert.equal(parsed.sourceSettings.layer_height,'0.24');
const normal=convertProject(parsed,parsed.plates[0].id,null,{target:'snapmaker'});
assert.doesNotMatch(dec.decode(normal.entries.get(SRC_BBL_PROJECT)),/SLICE ONLY|YAB3D_VIRTUAL_SLICE_ONLY/);
console.log('slice-only preparation: virtual tools, process overrides and normal export isolation passed');
