"""Rebuild the offline U1 profile catalogue from a pinned official release.

Only resolved profile data is downloaded; no upstream code is executed.
Machine G-code remains the application's existing U1 baseline.
"""
import json
from pathlib import Path
from urllib.request import urlopen
from urllib.parse import quote
from concurrent.futures import ThreadPoolExecutor

REV = 'b1831e5dcb464172de33783142425aafda834fbc'  # Snapmaker Orca v2.4.0
ROOT = Path(__file__).resolve().parents[1]
RAW = f'https://raw.githubusercontent.com/Snapmaker/OrcaSlicer/{REV}/'

def get(url):
    with urlopen(url, timeout=45) as response:
        return json.load(response)

def main():
    tree = get(f'https://api.github.com/repos/Snapmaker/OrcaSlicer/git/trees/{REV}?recursive=1')
    paths = [x['path'] for x in tree['tree'] if x['path'].startswith('resources/profiles/') and x['path'].endswith('.json')]
    index = get(RAW + 'resources/profiles/Snapmaker.json')
    cache = {}
    def resolve(path, trail=()):
        if path in trail:
            raise ValueError(f'Inheritance cycle: {path}')
        if path not in cache:
            cache[path] = get(RAW + quote(path))
        own = cache[path]
        parent = own.get('inherits')
        if not parent:
            return dict(own)
        candidates = [p for p in paths if p.endswith('/' + parent + '.json')]
        candidates.sort(key=lambda p: (not p.startswith('resources/profiles/Snapmaker/'), not p.startswith('resources/profiles/OrcaFilamentLibrary/'), p))
        if not candidates:
            raise ValueError(f'Missing parent {parent} in {path}')
        return {**resolve(candidates[0], trail + (path,)), **own}
    def entry(item):
        return resolve('resources/profiles/Snapmaker/' + item['sub_path'])
    selected = []
    for kind in ('machine', 'process', 'filament'):
        for item in index[kind + '_list']:
            name = item['name']
            if kind == 'machine' and name.startswith('Snapmaker U1 ('):
                selected.append((kind, item))
            elif kind == 'process' and '@Snapmaker U1 (' in name and ('Standard' in name or 'Color Mixing' in name):
                selected.append((kind, item))
            elif kind == 'filament' and (name.startswith('Generic ') or '@U1' in name) and not name.endswith('base'):
                selected.append((kind, item))
    with ThreadPoolExecutor(max_workers=6) as pool:
        resolved = list(pool.map(lambda pair: (pair[0], entry(pair[1])), selected))
    data = {'revision': REV, 'version': '2.4.0', 'machines': [], 'processes': [], 'filaments': []}
    metadata = {'inherits', 'from', 'type', 'instantiation', 'description', 'renamed_from', 'setting_id'}
    for kind, cfg in resolved:
        if cfg.get('instantiation') != 'true' or (kind == 'filament' and not any('Snapmaker U1 (' in p for p in cfg.get('compatible_printers', []))):
            continue
        if kind == 'machine':
            cfg = {k: v for k, v in cfg.items() if k in {'name', 'nozzle_diameter', 'min_layer_height', 'max_layer_height', 'nozzle_type'}}
        else:
            cfg = {k: v for k, v in cfg.items() if k not in metadata and 'gcode' not in k.lower()}
        data[{'machine':'machines','process':'processes','filament':'filaments'}[kind]].append(cfg)
    out = ROOT / 'web/shared/u1ProfileData.js'
    out.write_text('// Generated by tools/build_u1_profiles.py from Snapmaker Orca v2.4.0.\n'
                   '// Upstream profile data: AGPL-3.0; see THIRD_PARTY_NOTICES.txt.\n'
                   'export const U1_PROFILES = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
    print({k: len(data[k]) for k in ('machines','processes','filaments')})

if __name__ == '__main__':
    main()
