#!/usr/bin/env python3
"""Write the browser copy of the mixture model from the Python one.

    python tools/gen_mix_model.py

`u1mix_model.py` carries the MIT FilamentMixer coefficients (the same model
Strata ships, extracted from its reference source).  The browser needs the same
numbers to predict the same shades, and hand-transcribing 330 rows is how the two
applications would drift apart, so this generator writes `web/shared/mix_model.js`
and the parity test proves the two agree.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)

import u1mix_model as model                                     # noqa: E402

OUT = os.path.join(HERE, "web", "shared", "mix_model.js")

HEADER = """// FilamentMixer coefficients, generated from the MIT model in the Strata
// reference (src/js/89-texture-mixer.js, Justin Hayes, MIT) and kept identical
// to the Python copy in u1mix_model.py so both applications predict the same
// shades. Generated by tools/gen_mix_model.py -- do not hand-edit.
"""


def main() -> int:
    rows = [list(p) for p in model.POWERS]
    coefficients = [list(c) for c in model.COEFFICIENTS]
    if len(rows) != len(coefficients):
        raise SystemExit("the model's powers and coefficients disagree")
    text = (HEADER
            + "export const MIX_INTERCEPT = %s;\n" % json.dumps(list(model.INTERCEPT))
            + "export const MIX_POWERS = %s;\n" % json.dumps(rows)
            + "export const MIX_COEFFICIENTS = %s;\n" % json.dumps(coefficients))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"{OUT}: {len(text)} bytes, {len(rows)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
