// Builds two tiny fixtures for web/selftest.html:
//
//   selftest-fixture.3mf        a PrusaSlicer-style project (mesh inline,
//                               slic3rpe:mmu_segmentation, extruder_colour palette)
//   selftest-fixture-bambu.3mf  a Bambu/Orca-style project (mesh in 3D/Objects/,
//                               paint_color, project_settings.config) -- the shape
//                               Orca itself saves, and the one that exposes
//                               anything that reads the wrong document
import { writeFileSync } from "node:fs";
import { writeZip } from "./web/zip.js";

const enc = new TextEncoder();
const S = 10;                       // 20 mm cube
const corners = [
  [-S, -S, -S], [S, -S, -S], [S, S, -S], [-S, S, -S],
  [-S, -S, S], [S, -S, S], [S, S, S], [-S, S, S],
];
const faces = [
  [0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7],
  [0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5],
  [2, 3, 7], [2, 7, 6], [3, 0, 4], [3, 4, 7],
];
// first four facets extruder 1, next four extruder 2, rest on the base extruder
const paint = ["4", "4", "4", "4", "8", "8", "8", "8", null, null, null, null];

const vertices = corners.map(([x, y, z]) =>
  `     <vertex x="${x}" y="${y}" z="${z}"/>`).join("\n");
const triangles = (attrName) => faces.map(([a, b, c], i) => {
  const attr = paint[i] && attrName ? ` ${attrName}="${paint[i]}"` : "";
  return `     <triangle v1="${a}" v2="${b}" v3="${c}"${attr}/>`;
}).join("\n");

const cubeMesh = (attrName) => `<mesh>
    <vertices>
${vertices}
    </vertices>
    <triangles>
${triangles(attrName)}
    </triangles>
   </mesh>`;

const RELS = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`;

const TYPES = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
</Types>
`;

// ---------------------------------------------------------------- Prusa flavour
const prusaModel = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">
 <metadata name="slic3rpe:Version3mf">1</metadata>
 <metadata name="slic3rpe:MmPaintingVersion">1</metadata>
 <metadata name="Title">painted cube</metadata>
 <resources>
  <object id="1" type="model">
   ${cubeMesh("slic3rpe:mmu_segmentation")}
  </object>
 </resources>
 <build>
  <item objectid="1" transform="1 0 0 0 1 0 0 0 1 135 135 10"/>
 </build>
</model>
`;

const prusaPrint = `; generated by PrusaSlicer for the converter self-test

; extruder_colour = #FF8000;#008000
; filament_colour = #FF8000;#FF8000
; filament_type = PLA;PLA
; layer_height = 0.2
; printer_model = XL2IS
; support_material = 0
`;

const prusaModelConfig = `<?xml version="1.0" encoding="UTF-8"?>
<config>
 <object id="1" instances_count="1">
  <metadata type="object" key="name" value="cube.stl"/>
  <metadata type="object" key="extruder" value="2"/>
  <volume firstid="0" lastid="11">
   <metadata type="volume" key="name" value="cube.stl"/>
   <metadata type="volume" key="volume_type" value="ModelPart"/>
   <metadata type="volume" key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>
   <metadata type="volume" key="source_file" value="cube.stl"/>
   <mesh_stat edges_fixed="0" degenerate_facets="0" facets_removed="0" facets_reversed="0" backwards_edges="0"/>
  </volume>
 </object>
</config>
`;

const prusa = await writeZip([
  { name: "[Content_Types].xml", data: enc.encode(TYPES) },
  { name: "_rels/.rels", data: enc.encode(RELS) },
  { name: "3D/3dmodel.model", data: enc.encode(prusaModel) },
  { name: "Metadata/Slic3r_PE.config", data: enc.encode(prusaPrint) },
  { name: "Metadata/Slic3r_PE_model.config", data: enc.encode(prusaModelConfig) },
]);
writeFileSync("web/selftest-fixture.3mf", prusa);
console.log(`web/selftest-fixture.3mf        ${prusa.length} bytes (prusa, inline mesh)`);

// ---------------------------------------------------------------- Bambu flavour
const bblProject = {
  version: "0.0.0.0",
  from: "project",
  name: "project_settings",
  printer_model: "Snapmaker U1",
  printer_settings_id: "Snapmaker U1 (0.4 nozzle)",
  print_settings_id: "0.20mm Standard @Snapmaker U1 (0.4 nozzle)",
  layer_height: "0.2",
  enable_support: "1",
  support_type: "tree(auto)",
  support_threshold_angle: "30",
  enable_prime_tower: "1",
  wipe_tower_x: ["13"],
  wipe_tower_y: ["211"],
  prime_tower_width: "30",
  prime_tower_brim_width: "5",
  brim_type: "auto_brim",
  brim_width: "5",
  printable_area: ["0.5x1", "270.5x1", "270.5x271", "0.5x271"],
  printable_height: "270.05",
  filament_colour: ["#FF8000", "#008000", "#000000", "#FFFFFF"],
  filament_type: ["PLA", "PLA", "PLA", "PLA"],
  filament_settings_id: ["Snapmaker PLA Basic @U1", "Snapmaker PLA Basic @U1",
                         "Snapmaker PLA Basic @U1", "Snapmaker PLA Basic @U1"],
};

const bblModelSettings = `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <object id="5">
    <metadata key="name" value="cube.stl"/>
    <metadata key="extruder" value="2"/>
    <part id="1" subtype="normal_part">
      <metadata key="name" value="cube.stl"/>
      <metadata key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>
      <metadata key="source_file" value="cube.stl"/>
      <metadata key="extruder" value="2"/>
      <mesh_stat edges_fixed="0" degenerate_facets="0" facets_removed="0" facets_reversed="0" backwards_edges="0"/>
    </part>
  </object>
</config>
`;

const bblObject = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" requiredextensions="p">
 <metadata name="BambuStudio:3mfVersion">1</metadata>
 <resources>
  <object id="1" p:UUID="11111111-1111-4111-8111-111111111111" type="model">
   ${cubeMesh("paint_color")}
  </object>
 </resources>
 <build/>
</model>
`;

// the placement lives in <component> here, with identity on the <item>
const bblMain = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" requiredextensions="p">
 <metadata name="Application">Snapmaker Orca</metadata>
 <metadata name="BambuStudio:3mfVersion">1</metadata>
 <resources>
  <object id="5" p:UUID="22222222-2222-4222-8222-222222222222" type="model">
   <components>
    <component p:path="/3D/Objects/cube.model" objectid="1" p:UUID="33333333-3333-4333-8333-333333333333" transform="1 0 0 0 1 0 0 0 1 135 135 10"/>
   </components>
  </object>
 </resources>
 <build p:UUID="44444444-4444-4444-8444-444444444444">
  <item objectid="5" p:UUID="55555555-5555-4555-8555-555555555555" transform="1 0 0 0 1 0 0 0 1 0 0 0" printable="1"/>
 </build>
</model>
`;

const bblObjectRels = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/Objects/cube.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`;

const bblSliceInfo = `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header>
    <header_item key="X-BBL-Client-Type" value="slicer"/>
    <header_item key="X-BBL-Client-Version" value=""/>
  </header>
</config>
`;

const bambu = await writeZip([
  { name: "[Content_Types].xml", data: enc.encode(TYPES) },
  { name: "_rels/.rels", data: enc.encode(RELS) },
  { name: "3D/3dmodel.model", data: enc.encode(bblMain) },
  { name: "3D/_rels/3dmodel.model.rels", data: enc.encode(bblObjectRels) },
  { name: "3D/Objects/cube.model", data: enc.encode(bblObject) },
  { name: "Metadata/project_settings.config", data: enc.encode(JSON.stringify(bblProject, null, 4)) },
  { name: "Metadata/model_settings.config", data: enc.encode(bblModelSettings) },
  { name: "Metadata/slice_info.config", data: enc.encode(bblSliceInfo) },
]);
writeFileSync("web/selftest-fixture-bambu.3mf", bambu);
console.log(`web/selftest-fixture-bambu.3mf  ${bambu.length} bytes (bambu, mesh in Objects/)`);
